# Generated by Django 6.0.2 on 2026-02-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_seed_rbac_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
