# Generated by Django 5.2.8 on 2026-02-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_event_event_date'),
        ('api', '0005_remove_user_avatar_url_user_avatar'),
    ]

    operations = [
    ]
