# Generated by Django 6.0.2 on 2026-02-25 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import string
import secrets

def generate_affiliate_code():
    length = 8
    chars = string.ascii_uppercase + string.digits
    return ''.join(secrets.choice(chars) for _ in range(length))

def populate_affiliate_codes(apps, schema_editor):
    User = apps.get_model('api', 'User')
    for user in User.objects.all():
        if not user.affiliate_code:
            code = generate_affiliate_code()
            while User.objects.filter(affiliate_code=code).exists():
                code = generate_affiliate_code()
            user.affiliate_code = code
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_merge_20260225_1000"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="affiliate_code",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.RunPython(populate_affiliate_codes),
        migrations.AlterField(
            model_name="user",
            name="affiliate_code",
            field=models.CharField(blank=True, default='', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="affiliated_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="affiliates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="affiliation_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
