# Generated by Django 6.0.2 on 2026-03-03 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_location_user_music_preferences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_company', models.BooleanField(default=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_address', models.CharField(blank=True, max_length=500, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name_org', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name_org', models.CharField(blank=True, max_length=100, null=True)),
                ('fiscal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('employee_count', models.CharField(blank=True, choices=[('1-5', '1-5'), ('6-20', '6-20'), ('21-50', '21-50'), ('50+', '50+')], max_length=10, null=True)),
                ('event_types', models.JSONField(blank=True, default=list)),
                ('admin_onboarding_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
