# Generated by Django 6.0.2 on 2026-03-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_organizerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Bozza'), ('PUBLISHED', 'Pubblicato'), ('TO_BE_REFUNDED', 'Da Rimborsare'), ('CONCLUDED', 'Concluso'), ('ARCHIVED', 'Archiviato')], default='DRAFT', max_length=20),
        ),
    ]
