# Generated by Django 6.0.2 on 2026-03-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_event_event_date_event_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcategory',
            name='card_bg_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='card_bg_color2',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='card_bg_type',
            field=models.CharField(choices=[('solid', 'Fisso'), ('gradient', 'Gradiente')], default='solid', max_length=20),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/logos/'),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='sale_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='sale_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='sale_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='sale_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
