# Generated by Django 5.2.8 on 2025-11-12 11:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='code',
            field=models.CharField(default=api.models.generate_unique_code, max_length=10, unique=True),
        ),
    ]
