runtime: python311

entrypoint: gunicorn -b :$PORT getinvolved.wsgi:application

env_variables:
  DJANGO_SETTINGS_MODULE: getinvolved.settings
  PYTHONUNBUFFERED: "1"

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 2
